### ISSUE TITLE
TDD the PGN/Tag.ts class

### ISSUE THREAD

**Issue by programarivm** [chesslablab/ts-chess#12]
The [php-chess/src/PGN/Tag.php](https://github.com/chesslablab/php-chess/blob/master/src/PGN/Tag.php) file should be transcribed into a new .ts file in the [ts-chess/src/PGN](https://github.com/chesslablab/ts-chess/tree/master/src/PGN) folder called `Tag.ts`. This one is mainly intended to validate PGN tags to perform further database queries.

The coding conventions required to create `Tag.ts` are the same ones in place being used in these files:

- [`EnPassantTargetSquare.ts`](https://github.com/chesslablab/ts-chess/blob/master/src/FEN/field/EnPassantTargetSquare.ts)
- [`SideToMove.ts`](https://github.com/chesslablab/ts-chess/blob/master/src/FEN/field/SideToMove.ts)

Also you may want to look at the tests:

- [`EnPassantTargetSquare.test.ts`](https://github.com/chesslablab/ts-chess/blob/master/tests/unit/FEN/field/EnPassantTargetSquare.test.ts)
- [`SideToMove.test.ts`](https://github.com/chesslablab/ts-chess/blob/master/tests/unit/FEN/field/SideToMove.test.ts)

Happy learning and coding!

**Comment by owais34** [comment]
Hi please assign me this issue.
