### ISSUE TITLE
TDD the Bishop

### ISSUE THREAD

**Issue by programarivm** [chesslablab/ts-chess#14]
At this stage everything's ready to start writing the chess pieces!

Remember:

> We're writing an object-oriented chess codebase not only because we want to practice software development skills but also to avoid the intricacies of chess bitboards.

This issue is about TDDing the `mobility()` method in a new .ts file called `Bishop.ts` in the [ts-chess/src/piece](https://github.com/chesslablab/ts-chess/tree/master/src/piece) folder.

For further information, please visit:

- [TDD the Knight](https://github.com/chesslablab/ts-chess/issues/13)
- [What Does It Mean to TDD a Class?](https://bootcamp.uxdesign.cc/what-does-it-mean-to-tdd-a-class-4dbb9bd6b5e2)

Keep it up and happy coding and learning!

**Comment by owais34** [comment]
Hi assign me this issue !! 😁
