### ISSUE TITLE
TDD the square evaluation

### ISSUE THREAD

**Issue by programarivm** [chesslablab/ts-chess#29]
Now that the `calcMobility()` method has been successfully implemented in all chess pieces, let's start implementing the heuristic evaluation features! Remember, we're transcribing a statically-typed, object-oriented PHP codebase into TypeScript from scratch.

For further information please visit:

- [Why TypeScript and PHP Are Good Friends](https://medium.com/geekculture/why-typescript-and-php-are-good-friends-964360fb75f6)

This issue is about TDDing the square evaluation in a new .ts file called `SqEvaluation.ts` in the `ts-chess/src/evaluation` folder. The square evaluation will allow to find out which chessboard squares are being occupied by pieces of both colors and which ones are free at any given moment. 

For further details on how the square evaluation is implemented in PHP Chess please visit:

- [php-chess/src/Evaluation/SqEvaluation.php](https://github.com/chesslablab/php-chess/blob/master/src/Evaluation/SqEvaluation.php)
- [php-chess/tests/unit/Evaluation/SqEvaluationTest.php](https://github.com/chesslablab/php-chess/blob/master/tests/unit/Evaluation/SqEvaluationTest.php)

Keep it up and happy learning and coding!

**Comment by owais34** [comment]
Hi Please assign me this issue 😁!!
