### ISSUE TITLE
TDD the pressure evaluation

### ISSUE THREAD

**Issue by programarivm** [chesslablab/ts-chess#33]
Let's implement more heuristic evaluation features! Remember, we're transcribing a statically-typed, object-oriented PHP codebase into TypeScript from scratch.

For further information please visit:

- [Why TypeScript and PHP Are Good Friends](https://medium.com/geekculture/why-typescript-and-php-are-good-friends-964360fb75f6)

So far the following ones have been added to the codebase already:

- [Square evaluation](https://github.com/chesslablab/ts-chess/blob/master/src/evaluation/SqEvaluation.ts)

This issue is about TDDing the pressure evaluation in a new .ts file called `PressureEvaluation.ts` in the `ts-chess/src/evaluation` folder as well as the corresponding test file `PressureEvaluation.test.ts` in the `tests/unit/evaluation` folder. The pressure evaluation will allow to find out which squares are being threatened at any given moment.

For further details on how the pressure evaluation is implemented in PHP Chess please visit:

- [php-chess/src/Evaluation/PressureEvaluation.php](https://github.com/chesslablab/php-chess/blob/master/src/Evaluation/PressureEvaluation.php)
- [php-chess/tests/unit/Evaluation/PressureEvaluationTest.php](https://github.com/chesslablab/php-chess/blob/master/tests/unit/Evaluation/PressureEvaluationTest.php)

Keep it up and happy learning and coding!

**Comment by owais34** [comment]
Hi please assign this issue to me 😁 . Happy learning and coding !!
