### ISSUE TITLE
TDD the center evaluation

### ISSUE THREAD

**Issue by programarivm** [chesslablab/ts-chess#40]
Let's implement more heuristic evaluation features! Remember, we're transcribing a statically-typed, object-oriented PHP codebase into TypeScript from scratch.

For further information please visit:

- [Why TypeScript and PHP Are Good Friends](https://medium.com/geekculture/why-typescript-and-php-are-good-friends-964360fb75f6)

So far the following ones have been added to the codebase already:

- [Pressure evaluation](https://github.com/chesslablab/ts-chess/blob/master/src/eval/PressureEval.ts)
- [Space evaluation](https://github.com/chesslablab/ts-chess/blob/master/src/eval/SpaceEval.ts)
- [Square evaluation](https://github.com/chesslablab/ts-chess/blob/master/src/eval/SqEval.ts)

This issue is about TDDing the center evaluation in a new .ts file called `CenterEval.ts` in the `ts-chess/src/eval` folder as well as the corresponding test file `CenterEval.test.ts` in the `tests/unit/eval` folder.

For further details on how the center evaluation is implemented in PHP Chess please visit:

- [php-chess/src/Eval/CenterEval.php](https://github.com/chesslablab/php-chess/blob/master/src/Eval/CenterEval.php)
- [php-chess/tests/unit/Eval/CenterEvalTest.php](https://github.com/chesslablab/php-chess/blob/master/tests/unit/Eval/CenterEvalTest.php)

Keep it up and happy learning and coding!

**Comment by owais34** [comment]
Hi Please assign me this issue !! 😊 Happy coding and learning !!
