### ISSUE TITLE
TDD the connectivity evaluation

### ISSUE THREAD

**Issue by programarivm** [chesslablab/ts-chess#45]
Let's implement more heuristic evaluation features! Remember, we're transcribing a statically-typed, object-oriented PHP codebase into TypeScript from scratch.

For further information please visit:

- [Why TypeScript and PHP Are Good Friends](https://medium.com/geekculture/why-typescript-and-php-are-good-friends-964360fb75f6)

So far the following ones have been added to the codebase already:

- [Pressure evaluation](https://github.com/chesslablab/ts-chess/blob/master/src/eval/PressureEval.ts)
- [Space evaluation](https://github.com/chesslablab/ts-chess/blob/master/src/eval/SpaceEval.ts)
- [Square evaluation](https://github.com/chesslablab/ts-chess/blob/master/src/eval/SqEval.ts)
- [Material evaluation](https://github.com/chesslablab/ts-chess/blob/master/src/eval/MaterialEval.ts)
- [Center evaluation](https://github.com/chesslablab/ts-chess/blob/master/src/eval/CenterEval.ts)

This issue is about TDDing the connectivity evaluation in a new .ts file called `ConnectivityEval.ts` in the `ts-chess/src/eval` folder as well as the corresponding test file `ConnectivityEval.test.ts` in the `tests/unit/eval` folder.

For further details on how the connectivity evaluation is implemented in PHP Chess please visit:

- [php-chess/src/Eval/ConnectivityEval.php](https://github.com/chesslablab/php-chess/blob/master/src/Eval/ConnectivityEval.php)
- [php-chess/tests/unit/Eval/ConnectivityEvalTest.php](https://github.com/chesslablab/php-chess/blob/master/tests/unit/Eval/ConnectivityEvalTest.php)

Keep it up and happy learning and coding!

**Comment by owais34** [comment]
Hi Please assign me this issue 😁. Happy learning and coding !!
