### ISSUE TITLE
Replace let with const in the evaluation tests

### ISSUE THREAD

**Issue by programarivm** [chesslablab/ts-chess#73]
How to declare variables in JavaScript is a widely discussed topic, and way easier than it seems!

As you probably know, ES6 (EcmaScript 2015) provides you with three different ways to do that: `var`, `let` and `const`. Please note that `var` is not being used in the TypeScript Chess codebase whatsoever. So the question is, should variables be declared with either the `let` or with the `const` keyword?

As a rule of thumb `let` should be used as long as another value is to be reassigned to such variable; if that's not the case `const` should be used instead. Thus, the tests in the [tests/unit/eval](https://github.com/chesslablab/ts-chess/tree/master/tests/unit/eval) folder need to be updated to meet this requirement.

Keep it up and happy coding and learning.

**Comment by orrgorenn** [comment]
I would like to work on that!

**Comment by programarivm** [comment]
@orrgorenn welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/ts-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!
