### ISSUE TITLE
Replace let with const in the piece tests

### ISSUE THREAD

**Issue by programarivm** [chesslablab/ts-chess#74]
How to declare variables in JavaScript is a widely discussed topic, and way easier than it seems!

As you probably know, ES6 (EcmaScript 2015) provides you with three different ways to do that: `var`, `let` and `const`. Please note that `var` is not being used in the TypeScript Chess codebase whatsoever. So the question is, should variables be declared with either the `let` or with the `const` keyword?

As a rule of thumb `let` should be used as long as another value is to be reassigned to the variable; if that's not the case `const` should be used instead. Thus, the tests in the [tests/unit/piece](https://github.com/chesslablab/ts-chess/tree/master/tests/unit/piece) folder need to be updated to meet this requirement.

Keep it up and happy coding and learning.

**Comment by orrgorenn** [comment]
I would like to work on that!
