### ISSUE TITLE
TDD the Movetext class

### ISSUE THREAD

**Issue by programarivm** [chesslablab/ts-chess#84]
[Chess\PGN\Movetext](https://github.com/chesslablab/php-chess/blob/master/src/Movetext.php) provides with functionality to parse and process a PGN movetext. It should be transcribed into TypeScript accordingly in a new file called `Movetext.js` and the tests should be written in `tests/unit/Movetext.test.ts`.

For further information you may want to read the docs:

- [Chess\Movetext](https://php-chess.readthedocs.io/en/latest/movetext/)

Keep it up and happy coding and learning!

**Comment by owais34** [comment]
Hi Please assign me this issue 😁 . Happy learning and coding !!
