### ISSUE TITLE
TDD the PGN/Move.ts class

### ISSUE THREAD

**Issue by programarivm** [chesslablab/ts-chess#9]
The [php-chess/src/PGN/Move.php](https://github.com/chesslablab/php-chess/blob/master/src/PGN/Move.php) file should be transcribed into a new .ts file in the [ts-chess/src/PGN](https://github.com/chesslablab/ts-chess/tree/master/src/PGN) folder called `Move.ts`. This one is mainly intended to convert a PGN move in string format to an object for further processing.

The coding conventions required to create `Move.ts` are the same ones in place being used in these files:

- [`EnPassantTargetSquare.ts`](https://github.com/chesslablab/ts-chess/blob/master/src/FEN/field/EnPassantTargetSquare.ts)
- [`SideToMove.ts`](https://github.com/chesslablab/ts-chess/blob/master/src/FEN/field/SideToMove.ts)

Also you may want to look at the tests:

- [`EnPassantTargetSquare.test.ts`](https://github.com/chesslablab/ts-chess/blob/master/tests/unit/FEN/field/EnPassantTargetSquare.test.ts)
- [`SideToMove.test.ts`](https://github.com/chesslablab/ts-chess/blob/master/tests/unit/FEN/field/SideToMove.test.ts)

For further information, please visit:

- [Why TypeScript and PHP Are Good Friends](https://medium.com/geekculture/why-typescript-and-php-are-good-friends-964360fb75f6)

Happy learning and coding!

**Comment by owais34** [comment]
Hi please assign me this issue. Happy learning and coding.
