### ISSUE TITLE
TDD the defense evaluation

### ISSUE THREAD

**Issue by programarivm** [chesslablab/ts-chess#91]
Let's implement more heuristic evaluation features! Remember, we're transcribing a statically-typed, object-oriented PHP codebase into TypeScript from scratch. This issue is about TDDing the defense evaluation in a new .ts file called `DefenseEval.ts` in the `ts-chess/src/eval` folder as well as the corresponding test file `DefenseEval.test.ts` in the `tests/unit/eval` folder.

For further details on how the defense evaluation is implemented in PHP Chess please visit:

- [php-chess/src/Eval/DefenseEval.php](https://github.com/chesslablab/php-chess/blob/master/src/Eval/DefenseEval.php)
- [php-chess/tests/unit/Eval/DefenseEvalTest.php](https://github.com/chesslablab/php-chess/blob/master/tests/unit/Eval/DefenseEvalTest.php)

Keep it up and happy learning and coding!

**Comment by owais34** [comment]
Hi Please assign me this issue 😁 . Happy learning and coding !!
